using System;
using System.Collections.Generic;
using System.Text;

namespace DrawIt
{
    public static class Constants
    {
        public static Dictionary<string, string> Colors = new Dictionary<string, string>()
        {
            { "maroon", "FF800000"  },
            {"dark red", "FF8B0000"  },
            {"brown", "FFA52A2A"  },
            {"firebrick", "FFB22222"  },
            {"crimson", "FFDC143C"  },
            {"red", "FFFF0000"  },
            {"tomato", "FFFF6347"  },
            {"coral", "FFFF7F50"  },
            {"indian red", "FFCD5C5C"  },
            {"light coral", "FFF08080"  },
            {"dark salmon", "FFE9967A"  },
            {"salmon", "FFFA8072"  },
            {"light salmon", "FFFFA07A"  },
            {"orange red", "FFFF4500"  },
            {"dark orange", "FFFF8C00"  },
            {"orange", "FFFFA500"  },
            {"gold", "FFFFD700"  },
            {"dark golden rod", "FFB8860B"  },
            {"golden rod","B8860B"  },
            {"pale golden rod", "FFEEE8AA"  },
            {"dark khaki", "FFBDB76B"  },
            {"khaki", "FFF0E68C"  },
            {"olive", "FF808000"  },
            {"yellow", "FFFFFF00"  },
            {"yellow green", "FF9ACD32"  },
            {"dark olive green", "FF556B2F"  },
            {"olive drab", "FF6B8E23"  },
            {"lawn green", "FF7CFC00"  },
            {"chart reuse", "FF7FFF00"  },
            {"green yellow", "FFADFF2F"  },
            {"dark green", "FF006400"  },
            {"green", "FF008000"  },
            {"forest green", "FF228B22"  },
            {"lime", "FF00FF00"  },
            {"lime green", "FF32CD32"  },
            {"light green", "FF90EE90"  },
            {"pale green", "FF98FB98"  },
            {"dark sea green", "FF8FBC8F"  },
            {"medium spring green", "FF00FA9A"  },
            {"spring green", "FF00FF7F"  },
            {"sea green", "FF2E8B57"  },
            {"medium aqua marine", "FF66CDAA"  },
            {"medium sea green", "FF3CB371"  },
            {"light sea green", "FF20B2AA"  },
            {"dark slate gray", "FF2F4F4F"  },
            {"teal", "FF008080"  },
            {"dark cyan", "FF008B8B"  },
            {"aqua", "FF00FFFF"  },
            {"cyan", "FF00FFFF"  },
            {"light cyan", "FFE0FFFF"  },
            {"dark turquoise", "FF00CED1"  },
            {"turquoise", "FF40E0D0"  },
            {"medium turquoise", "FF48D1CC"  },
            {"pale turquoise", "FFAFEEEE"  },
            {"aqua marine", "FF7FFFD4"  },
            {"powder blue", "FFB0E0E6"  },
            {"cadet blue", "FF5F9EA0"  },
            {"steel blue", "FF4682B4"  },
            {"corn flower blue", "FF6495ED"  },
            {"deep sky blue", "FF00BFFF"  },
            {"dodger blue", "FF1E90FF"  },
            {"light blue", "FFADD8E6"  },
            {"sky blue", "FF87CEEB"  },
            {"light sky blue", "FF87CEFA"  },
            {"midnight blue", "FF191970"  },
            {"navy", "FF000080"  },
            {"dark blue", "FF00008B"  },
            {"medium blue", "FF0000CD"  },
            {"blue", "FF0000FF"  },
            {"royal blue", "FF4169E1"  },
            {"blue violet", "FF8A2BE2"  },
            {"indigo", "FF4B0082"  },
            {"dark slate blue", "FF483D8B"  },
            {"slate blue", "FF6A5ACD"  },
            {"medium slate blue", "FF7B68EE"  },
            {"medium purple", "FF9370DB"  },
            {"dark magenta", "FF8B008B"  },
            {"dark violet", "FF9400D3"  },
            {"dark orchid", "FF9932CC"  },
            {"medium orchid", "FFBA55D3"  },
            {"purple", "FF800080"  },
            {"thistle", "FFD8BFD8"  },
            {"plum", "FFDDA0DD"  },
            {"violet", "FFEE82EE"  },
            {"magenta / fuchsia", "FFFF00FF"  },
            {"orchid", "FFDA70D6"  },
            {"medium violet red", "FFC71585"  },
            {"pale violet red", "FFDB7093"  },
            {"deep pink", "FFFF1493"  },
            {"hot pink", "FFFF69B4"  },
            {"light pink", "FFFFB6C1"  },
            {"pink", "FFFFC0CB"  },
            {"antique white", "FFFAEBD7"  },
            {"beige", "FFF5F5DC"  },
            {"bisque", "FFFFE4C4"  },
            {"blanched almond", "FFFFEBCD"  },
            {"wheat", "FFF5DEB3"  },
            {"corn silk", "FFFFF8DC"  },
            {"lemon chiffon", "FFFFFACD"  },
            {"light golden rod yellow", "FFFAFAD2"  },
            {"light yellow", "FFFFFFE0"  },
            {"saddle brown", "FF8B4513"  },
            {"sienna", "FFA0522D"  },
            {"chocolate", "FFD2691E"  },
            {"peru", "FFCD853F"  },
            {"sandy brown", "FFF4A460"  },
            {"burly wood", "FFDEB887"  },
            {"tan", "FFD2B48C"  },
            {"rosy brown", "FFBC8F8F"  },
            {"moccasin", "FFFFE4B5"  },
            {"navajo white", "FFFFDEAD"  },
            {"peach puff", "FFFFDAB9"  },
            {"misty rose", "FFFFE4E1"  },
            {"lavender blush", "FFFFF0F5"  },
            {"linen", "FFFAF0E6"  },
            {"old lace", "FFFDF5E6"  },
            {"papaya whip", "FFFFEFD5"  },
            {"sea shell", "FFFFF5EE"  },
            {"mint cream", "FFF5FFFA"  },
            {   "slate gray",   "FF708090"  },
            {"light slate gray", "FF778899"  },
            {"light steel blue", "FFB0C4DE"  },
            {"lavender", "FFE6E6FA"  },
            {"floral white", "FFFFFAF0"  },
            {"alice blue", "FFF0F8FF"  },
            {"ghost white", "FFF8F8FF"  },
            {"honeydew", "FFF0FFF0"  },
            {"ivory", "FFFFFFF0"  },
            {"azure", "FFF0FFFF"  },
            {"snow", "FFFFFAFA"  },
            {"black", "FF000000"  },
            {"dim gray / dim grey", "FF696969"  },
            {"gray", "FF808080"  },
            {"dark gray / dark grey", "FFA9A9A9"  },
            {"silver", "FFC0C0C0"  },
            {"light gray", "FFD3D3D3"  },
            {"gainsboro", "FFDCDCDC"  },
            {"white smoke", "FFF5F5F5"  },
            {"white", "FFFFFFFF"  }
            };
    }
}
